//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rtt.ErrorHandler.Models.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_WebEvent_ErrorCodes
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int EventCode { get; set; }
        public string Level { get; set; }
    }
}
