//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rtt.ErrorHandler.Models.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string FIRST_NAME { get; set; }
        public string INITIALS { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string TELH { get; set; }
        public string TELW { get; set; }
        public string MOBILE { get; set; }
        public string POSTAL_ADDRESS_1 { get; set; }
        public string POSTAL_ADDRESS_2 { get; set; }
        public string POSTAL_SUBURB { get; set; }
        public string POSTAL_CODE { get; set; }
        public string STREET_ADDRESS_1 { get; set; }
        public string STREET_ADDRESS_2 { get; set; }
        public string SUBURB { get; set; }
        public string CITY { get; set; }
        public string STREET_CODE { get; set; }
        public string COUNTRY { get; set; }
    }
}
